name: Test
on:
  # schedule:
  #   - cron: '0 0 * * 5'
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**.yml'

jobs:
  update_data:
    runs-on: ubuntu-latest
    env:
      MAIN_DIRECTORY: "/home/runner/work/imgGen/imgGen"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: peanutkim/imgGen
          ref: 'develop'
        
      
      - name: Parse HTML
        run: |
          pwd
          python -u ${{ env.MAIN_DIRECTORY }}/test.py
          git config user.email "hammsowon@gmail.com"
          git config user.name "Irosora"
          git add .
          git commit -m "Update the HTML file"
          git push